config/routes.rb
Rails.application.routes.draw do
  
  resources :restaurants, except: [:delete]

  # # READ
  # # GET a list of restaurants
  # get "restaurants", to: "restaurants#index"

  # # GET a single restaurant
  # get "restaurants/:id", to: "restaurants#show"


  # # CREATE
  # # Display the restaurant FORM 
  # get "restaurants/new", to: "restaurants#new"
  
  # # Process the new form
  # post "restaurants", to: "restaurants#create"

  # #UPDATE
  # # Display the update form
  # get "restaurants/:id/edit", to: "restaurants#edit"

  # # Process the update form
  # put "restaurants/:id", to: "restaurants#update"
  # patch "restaurants/:id", to: "restaurants#update"


  # # DELETE
  # delete "restaurants/:id", to: "restaurants#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  def rating_good?
    if (rating)
      rating > 4
    else  
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index         # GET /restaurants
    @restaurants = Restaurant.all
  end

  def show          # GET /restaurants/:id
    # params[:id]
  end

  # Display the form
  def new           # GET /restaurants/new
    @restaurant = Restaurant.new
  end

  # Process the form
  def create        # POST /restaurants
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save

    redirect_to restaurant_path(@restaurant)
  end

  def edit          # GET /restaurants/:id/edit
  end

  def update        # PATCH /restaurants/:id
    @restaurant.update(restaurant_params)
    @restaurant.save

    redirect_to restaurant_path(@restaurant)
  end

  def destroy       # DELETE /restaurants/:id
    @restaurant.destroy

    redirect_to restaurants_path
  end

  private

  # Strong params for security reasons
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rateme</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :rating %>
  <%= f.text_field :rating %>

  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

app/views/restaurants/index.html.erb
<% @restaurants.each do |restaurant| %>
  <div>
    <%= link_to(restaurant.name, restaurant_path(restaurant)) %> - 
    <%= restaurant.address %>
    </div>
<% end %>
<%= link_to "Add New", new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= render 'form' %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.address %></p>

<%= link_to "Back to list", restaurants_path %>
<%= link_to "Delete", restaurant_path(@restaurant),
      method: :delete,
      data: { confirm: "Are you sure?" } %>